//Welcome to the grand wall of text!
//This script holds what EVERY item does. 
//This script is ran whenever an item in your inventory is clicked.
//If you want to program functionality to an item on click this is where you put it.
//Just check what item is being held and then put whatever you want!

//SLOT 1 Weapon
if item = 101 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else
if item = 102 {if global.acclvbase > 4 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 103 {if global.acclvbase > 9 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 104 {if global.acclvbase > 14 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 105 {if global.acclvbase > 19 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 106 {if global.acclvbase > 24 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 107 {if global.acclvbase > 29 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 108 {if global.acclvbase > 34 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 109 {if global.acclvbase > 39 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 110 {if global.acclvbase > 44 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 111 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else
if item = 112 {if global.acclvbase > 4 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 113 {if global.acclvbase > 9 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 114 {if global.acclvbase > 14 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 115 {if global.acclvbase > 19 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 116 {if global.acclvbase > 24 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 117 {if global.acclvbase > 29 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 118 {if global.acclvbase > 34 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 119 {if global.acclvbase > 39 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 120 {if global.acclvbase > 44 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 121 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else
if item = 122 {if global.acclvbase > 4 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 123 {if global.acclvbase > 9 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 124 {if global.acclvbase > 14 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 125 {if global.acclvbase > 19 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 126 {if global.acclvbase > 24 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 127 {if global.acclvbase > 29 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 128 {if global.acclvbase > 34 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 129 {if global.acclvbase > 39 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 130 {if global.acclvbase > 44 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 131 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else
if item = 132 {if global.acclvbase > 4 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 133 {if global.acclvbase > 9 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 134 {if global.acclvbase > 14 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 135 {if global.acclvbase > 19 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 136 {if global.acclvbase > 24 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 137 {if global.acclvbase > 29 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 138 {if global.acclvbase > 34 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 139 {if global.acclvbase > 39 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 140 {if global.acclvbase > 44 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 141 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else
if item = 142 {if global.acclvbase > 4 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 143 {if global.acclvbase > 9 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 144 {if global.acclvbase > 14 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 145 {if global.acclvbase > 19 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 146 {if global.acclvbase > 24 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 147 {if global.acclvbase > 29 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 148 {if global.acclvbase > 34 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 149 {if global.acclvbase > 39 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 150 {if global.acclvbase > 44 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 151 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else
if item = 152 {if global.acclvbase > 4 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 153 {if global.acclvbase > 9 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 154 {if global.acclvbase > 14 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 155 {if global.acclvbase > 19 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 156 {if global.acclvbase > 24 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 157 {if global.acclvbase > 29 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 158 {if global.acclvbase > 34 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 159 {if global.acclvbase > 39 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 160 {if global.acclvbase > 44 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 936 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else

//SLOT 2 Helm
if item = 201 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else
if item = 202 {if global.deflvbase > 4 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 203 {if global.deflvbase > 9 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 204 {if global.deflvbase > 14 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 205 {if global.deflvbase > 19 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 206 {if global.deflvbase > 24 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 207 {if global.deflvbase > 29 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 208 {if global.deflvbase > 34 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 209 {if global.deflvbase > 39 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 210 {if global.deflvbase > 44 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 211 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else
if item = 212 {if global.deflvbase > 4 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 213 {if global.deflvbase > 9 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 214 {if global.deflvbase > 14 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 215 {if global.deflvbase > 19 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 216 {if global.deflvbase > 24 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 217 {if global.deflvbase > 29 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 218 {if global.deflvbase > 34 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 219 {if global.deflvbase > 39 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 220 {if global.deflvbase > 44 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 331 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else
if item = 332 {if global.deflvbase > 4 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 333 {if global.deflvbase > 9 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 334 {if global.deflvbase > 14 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 335 {if global.deflvbase > 19 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 336 {if global.deflvbase > 24 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 337 {if global.deflvbase > 29 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 338 {if global.deflvbase > 34 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 339 {if global.deflvbase > 39 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 340 {if global.deflvbase > 44 {if global.armor2!=0 {scr_swap_item2(global.armor2)} else {global.hold=global.armor2 global.armor2=item global.item=global.armor2 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else

//SLOT 3 Body

if item = 221 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else
if item = 222 {if global.deflvbase > 4 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 223 {if global.deflvbase > 9 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 224 {if global.deflvbase > 14 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 225 {if global.deflvbase > 19 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 226 {if global.deflvbase > 24 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 227 {if global.deflvbase > 29 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 228 {if global.deflvbase > 34 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 229 {if global.deflvbase > 39 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 230 {if global.deflvbase > 44 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 231 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else
if item = 232 {if global.deflvbase > 4 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield  a "+string(obj_controller.text[item])+".",c_black)} else
if item = 233 {if global.deflvbase > 9 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 234 {if global.deflvbase > 14 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 235 {if global.deflvbase > 19 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 236 {if global.deflvbase > 24 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 237 {if global.deflvbase > 29 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 238 {if global.deflvbase > 34 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 239 {if global.deflvbase > 39 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 240 {if global.deflvbase > 44 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 311 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else
if item = 312 {if global.deflvbase > 4 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield  a "+string(obj_controller.text[item])+".",c_black)} else
if item = 313 {if global.deflvbase > 9 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 314 {if global.deflvbase > 14 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 315 {if global.deflvbase > 19 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 316 {if global.deflvbase > 24 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 317 {if global.deflvbase > 29 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 318 {if global.deflvbase > 34 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 319 {if global.deflvbase > 39 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 320 {if global.deflvbase > 44 {if global.armor3!=0 {scr_swap_item3(global.armor3)} else {global.hold=global.armor3 global.armor3=item global.item=global.armor3 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else

//SLOT 4 Legs

if item = 241 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else
if item = 242 {if global.deflvbase > 4 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 243 {if global.deflvbase > 9 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 244 {if global.deflvbase > 14 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 245 {if global.deflvbase > 19 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 246 {if global.deflvbase > 24 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 247 {if global.deflvbase > 29 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 248 {if global.deflvbase > 34 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 249 {if global.deflvbase > 39 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 250 {if global.deflvbase > 44 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 251 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else
if item = 252 {if global.deflvbase > 4 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 253 {if global.deflvbase > 9 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 254 {if global.deflvbase > 14 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 255 {if global.deflvbase > 19 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 256 {if global.deflvbase > 24 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 257 {if global.deflvbase > 29 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 258 {if global.deflvbase > 34 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 259 {if global.deflvbase > 39 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 260 {if global.deflvbase > 44 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 321 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else
if item = 322 {if global.deflvbase > 4 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 323 {if global.deflvbase > 9 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 324 {if global.deflvbase > 14 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 325 {if global.deflvbase > 19 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 326 {if global.deflvbase > 24 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 327 {if global.deflvbase > 29 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 328 {if global.deflvbase > 34 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 329 {if global.deflvbase > 39 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 330 {if global.deflvbase > 44 {if global.armor4!=0 {scr_swap_item4(global.armor4)} else {global.hold=global.armor4 global.armor4=item global.item=global.armor4 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else

//SLOT 5 Boots

if item = 261 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else
if item = 262 {if global.deflvbase > 4 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 263 {if global.deflvbase > 9 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 264 {if global.deflvbase > 14 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 265 {if global.deflvbase > 19 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 266 {if global.deflvbase > 24 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 267 {if global.deflvbase > 29 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 268 {if global.deflvbase > 34 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 269 {if global.deflvbase > 39 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 270 {if global.deflvbase > 44 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 915 {if global.deflvbase > 0 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 1 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 935 {if global.deflvbase > 9 {if global.armor5!=0 {scr_swap_item5(global.armor5)} else {global.hold=global.armor5 global.armor5=item global.item=global.armor5 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else

//SLOT 6 Sheild

if item = 271 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else
if item = 272 {if global.deflvbase > 4 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 273 {if global.deflvbase > 9 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 274 {if global.deflvbase > 14 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 275 {if global.deflvbase > 19 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 276 {if global.deflvbase > 24 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 277 {if global.deflvbase > 29 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 278 {if global.deflvbase > 34 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 279 {if global.deflvbase > 39 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 280 {if global.deflvbase > 44 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 281 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else
if item = 282 {if global.deflvbase > 4 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 5 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 283 {if global.deflvbase > 9 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 284 {if global.deflvbase > 14 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 15 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 285 {if global.deflvbase > 19 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 20 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 286 {if global.deflvbase > 24 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 25 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 287 {if global.deflvbase > 29 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 30 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 288 {if global.deflvbase > 34 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 35 to wield an "+string(obj_controller.text[item])+".",c_black)} else
if item = 289 {if global.deflvbase > 39 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 40 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 290 {if global.deflvbase > 44 {if global.armor6!=0 {scr_swap_item6(global.armor6)} else {global.hold=global.armor6 global.armor6=item global.item=global.armor6 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 45 to wield a "+string(obj_controller.text[item])+".",c_black)} else

//SLOT 7 Amulet

if item = 291 {if global.hplvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a hitpoints level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 292 {if global.acclvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need an accuracy level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 293 {if global.strlvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a strength level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 294 {if global.deflvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 295 {if global.mininglvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a mining level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 296 {if global.woodlvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a pioneering level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 297 {if global.fishlvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a fishing level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 298 {if global.cooklvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a cooking level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 299 {if global.craftlvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a craftsmanship level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 300 {if global.tamelvbase > 9 {if global.armor7!=0 {scr_swap_item7(global.armor7)} else {global.hold=global.armor7 global.armor7=item global.item=global.armor7 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a taming level of 10 to wield a "+string(obj_controller.text[item])+".",c_black)} else

//SLOT 8 Cape

if item = 301 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 302 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 303 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 304 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 305 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 306 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 307 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 308 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else
if item = 309 {if global.deflvbase > 0 {if global.armor8!=0 {scr_swap_item8(global.armor8)} else {global.hold=global.armor8 global.armor8=item global.item=global.armor8 global.hold=0 scr_remove_item()}} else scr_addmessage("You need a defense level of 0 to wield a "+string(obj_controller.text[item])+".",c_black)} else

//Food

if item = 751 {heal = 2 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 752 {heal = 4 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 753 {heal = 6 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 754 {heal = 8 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 755 {heal = 10 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 756 {heal = 12 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 757 {heal = 14 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 758 {heal = 16 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 759 {heal = 18 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else
if item = 760 {heal = 20 if global.hplv < global.hplvbase-heal+1 {global.hplv+=heal} else {global.hplv = global.hplvbase} scr_addmessage("You eat the "+string(obj_controller.text[item])+".",c_black) scr_remove_item()} else


//MISC

if item = 901 {if floor(random(10)) = 0 scr_addmessage ("I ate the bones!!",c_black) else scr_addmessage("You bury the bones in the ground.",c_black) scr_remove_item()} else
if item = 902 {if global.opentab = 5 {global.opentab = 0} else {global.opentab = 5}} else
if item = 903 {if global.opentab = 5 {global.opentab = 0} else {global.opentab = 5}} else
if item = 904 {if global.opentab = 5 {global.opentab = 0} else {global.opentab = 5}} else
if item = 905 {scr_dig_locations()} else
if item = 906 {if global.opentab = 5 {global.opentab = 0} else {global.opentab = 5}} else
if item = 907 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else
if item = 908 {if global.armor1!=0 {scr_swap_item(global.armor1)} else {global.hold=global.armor1 global.armor1=item global.item=global.armor1 global.hold=0 scr_remove_item()}} else
if item = 909 {if instance_number(obj_bobber) = 0 {instance_create(obj_player.x,obj_player.y,obj_bobber) scr_addmessage("You cast your line.",c_black)}} else
if item = 912 {if global.opentab = 5 {global.opentab = 0} else {global.opentab = 5}} else
if item = 914 {url_open_ext("http://www.celestia-game.wikia.com",1) url_open_ext("https://www.youtube.com/watch?v=9xL16Xj74WE",1)} else
if item = 916 {if global.quest2 = 1 {obj_player.x = obj_middle_of_ocean.x obj_player.y = obj_middle_of_ocean.y  scr_addmessage("A mystical force overwhelms you.",c_black)} else {scr_addmessage("The book is written in an unknown language.",c_black)}} else
if item = 926 {scr_addmessage("You read the book about hitpoints and gain "+string(global.hplvbase*10)+" xp!",c_black) global.hpxp-=global.hplvbase*10 scr_remove_item()} else
if item = 927 {scr_addmessage("You read the book about accuracy and gain "+string(global.acclvbase*10)+" xp!",c_black) global.accxp-=global.acclvbase*10 scr_remove_item()} else
if item = 928 {scr_addmessage("You read the book about strength and gain "+string(global.strlvbase*10)+" xp!",c_black) global.strxp-=global.strlvbase*10 scr_remove_item()} else
if item = 929 {scr_addmessage("You read the book about defence and gain "+string(global.deflvbase*10)+" xp!",c_black) global.defxp-=global.deflvbase*10 scr_remove_item()} else
if item = 930 {scr_addmessage("You read the book about mining and gain "+string(global.mininglvbase*10)+" xp!",c_black) global.miningxp-=global.mininglvbase*10 scr_remove_item()} else
if item = 931 {scr_addmessage("You read the book about pioneering and gain "+string(global.woodlvbase*10)+" xp!",c_black) global.woodxp-=global.woodlvbase*10 scr_remove_item()} else
if item = 932 {scr_addmessage("You read the book about fishing and gain "+string(global.fishlvbase*10)+" xp!",c_black) global.fishxp-=global.fishlvbase*10 scr_remove_item()} else
if item = 933 {scr_addmessage("You read the book about cooking and gain "+string(global.cooklvbase*10)+" xp!",c_black) global.cookxp-=global.cooklvbase*10 scr_remove_item()} else
if item = 934 {scr_addmessage("You read the book about crafting and gain "+string(global.craftlvbase*10)+" xp!",c_black) global.craftxp-=global.craftlvbase*10 scr_remove_item()} else
if item = 937 {scr_addmessage("You read the book about taming and gain "+string(global.tamelvbase*10)+" xp!",c_black) global.tamexp-=global.tamelvbase*10 scr_remove_item()} else

if item != 0
scr_addmessage("You can't do anything with a "+string(obj_controller.text[item]),c_black)
