if global.inv1=0 {global.inv1=item } else
if global.inv2=0 {global.inv2=item } else
if global.inv3=0 {global.inv3=item } else
if global.inv4=0 {global.inv4=item } else
if global.inv5=0 {global.inv5=item } else
if global.inv6=0 {global.inv6=item } else
if global.inv7=0 {global.inv7=item } else
if global.inv8=0 {global.inv8=item } else
if global.inv9=0 {global.inv9=item } else
if global.inv10=0 {global.inv10=item } else
if global.inv11=0 {global.inv11=item } else
if global.inv12=0 {global.inv12=item } else
if global.inv13=0 {global.inv13=item } else
if global.inv14=0 {global.inv14=item } else
if global.inv15=0 {global.inv15=item } else
if global.inv16=0 {global.inv16=item } else
if global.inv17=0 {global.inv17=item } else
if global.inv18=0 {global.inv18=item } else
if global.inv19=0 {global.inv19=item } else
if global.inv20=0 {global.inv20=item } else
if global.inv21=0 {global.inv21=item } else
if global.inv22=0 {global.inv22=item } else
if global.inv23=0 {global.inv23=item } else
if global.inv24=0 {global.inv24=item } else
if global.inv25=0 {global.inv25=item }
