//Used to swap items between inventory slots

if object_index = obj_slot1 {global.select1 = 1 global.selectid1 = global.inv1}
if object_index = obj_slot2 {global.select1 = 2 global.selectid1 = global.inv2}
if object_index = obj_slot3 {global.select1 = 3 global.selectid1 = global.inv3}
if object_index = obj_slot4 {global.select1 = 4 global.selectid1 = global.inv4}
if object_index = obj_slot5 {global.select1 = 5 global.selectid1 = global.inv5}
if object_index = obj_slot6 {global.select1 = 6 global.selectid1 = global.inv6}
if object_index = obj_slot7 {global.select1 = 7 global.selectid1 = global.inv7}
if object_index = obj_slot8 {global.select1 = 8 global.selectid1 = global.inv8}
if object_index = obj_slot9 {global.select1 = 9 global.selectid1 = global.inv9}
if object_index = obj_slot10 {global.select1 = 10 global.selectid1 = global.inv10}
if object_index = obj_slot11 {global.select1 = 11 global.selectid1 = global.inv11}
if object_index = obj_slot12 {global.select1 = 12 global.selectid1 = global.inv12}
if object_index = obj_slot13 {global.select1 = 13 global.selectid1 = global.inv13}
if object_index = obj_slot14 {global.select1 = 14 global.selectid1 = global.inv14}
if object_index = obj_slot15 {global.select1 = 15 global.selectid1 = global.inv15}
if object_index = obj_slot16 {global.select1 = 16 global.selectid1 = global.inv16}
if object_index = obj_slot17 {global.select1 = 17 global.selectid1 = global.inv17}
if object_index = obj_slot18 {global.select1 = 18 global.selectid1 = global.inv18}
if object_index = obj_slot19 {global.select1 = 19 global.selectid1 = global.inv19}
if object_index = obj_slot20 {global.select1 = 20 global.selectid1 = global.inv20}
if object_index = obj_slot21 {global.select1 = 21 global.selectid1 = global.inv21}
if object_index = obj_slot22 {global.select1 = 22 global.selectid1 = global.inv22}
if object_index = obj_slot23 {global.select1 = 23 global.selectid1 = global.inv23}
if object_index = obj_slot24 {global.select1 = 24 global.selectid1 = global.inv24}
if object_index = obj_slot25 {global.select1 = 25 global.selectid1 = global.inv25}
if object_index = obj_craft1 {global.select1 = 26 global.selectid1 = global.craft1}
if object_index = obj_craft2 {global.select1 = 27 global.selectid1 = global.craft2}
if object_index = obj_craft3 {global.select1 = 28 global.selectid1 = global.craft3}
if object_index = obj_craft4 {global.select1 = 29 global.selectid1 = global.craft4}
if object_index = obj_craft5 {global.select1 = 30 global.selectid1 = global.craft5}
if object_index = obj_craft6 {global.select1 = 31 global.selectid1 = global.craft6}
if object_index = obj_craft7 {global.select1 = 32 global.selectid1 = global.craft7}
if object_index = obj_craft8 {global.select1 = 33 global.selectid1 = global.craft8}
if object_index = obj_craft9 {global.select1 = 34 global.selectid1 = global.craft9}
